services:
  photo-kiosk:
    image: ssg-kiosk-photo-player:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-kiosk
    restart: unless-stopped
    ports:
      - "${KIOSK_PORT:-3000}:3000"
    volumes:
      - ./photos:/app/photos
      - ./public:/app/public
      - ./pages:/app/pages
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=${KIOSK_NODE_ENV}
      - PORT=${KIOSK_PORT}
      - OPENWEATHER_KEY=${KIOSK_OPENWEATHER_KEY}
      - ENV_PATH=/app/.env
      - CLIENT_ID=${CLIENT_ID:-${HOSTNAME:-${HOST:-${COMPUTERNAME:-default-client}}}}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro   # <-- ensure your file is used
    environment:
      - MTX_LOGLEVEL=info

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    profiles: [production]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
