services:
  media-slideshow-hub:
    image: ssg-media-slideshow-hub:latest
    container_name: media-slideshow-hub
    restart: unless-stopped
    network_mode: host

    ports:
      - "${DISPLAY_HUB_PORT:-3000}:3000"

    volumes:
      - ./media/photos:/app/media/photos
      - ./media/videos:/app/media/videos
      - ./media/movies:/app/media/movies
      - ./media/tv:/app/media/tv
      - ./runtime/logs:/app/runtime/logs
      - ./runtime/cache:/app/runtime/cache

      - ./database/config.yaml:/app/database/config.yaml:ro
      - ./public:/app/public
      - ./pages:/app/pages

      # Credentials for Google API
      - ${GOOGLE_CREDENTIALS_FILE:-/home/john/.gsecrets/gsheets-credentials.json}:/run/secrets/gsheets-credentials.json:ro

    env_file:
      - ~/.env
      - .env

    environment:
      - NODE_ENV=production
      - PORT=${DISPLAY_HUB_PORT:-3000}
      - CLIENT_ID=${CLIENT_ID}
      - ENV_PATH=/app/.env
      - GOOGLE_CREDENTIALS_PATH=/run/secrets/gsheets-credentials.json
      - GOOGLE_API_SCOPES=${GOOGLE_API_SCOPES}

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8888:8888"
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    profiles: [production]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
